# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# Users information
user1 = User.create(name: 'Tom', photo: 'image_profile.jpg', bio: 'Teacher from Mexico.')
user2 = User.create(name: 'Lilly', photo: 'image_profile.jpg', bio: 'Teacher from Poland.')
user3 = User.create(name: 'Sandra', photo: 'image_profile.jpg', bio: 'Student from Poland.')
user4 = User.create(name: 'Peter', photo: 'image_profile.jpg', bio: 'Politician from UK.')
user5 = User.create(name: 'John', photo: 'image_profile.jpg', bio: 'Teacher from UK.')

#Posts information
apost1 = Post.create(author: user1, title: 'Tom Post 1', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
apost2 = Post.create(author: user1, title: 'Tom Post 2', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
apost3 = Post.create(author: user1, title: 'Tom Post 3', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
apost4 = Post.create(author: user1, title: 'Tom Post 4', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
apost5 = Post.create(author: user1, title: 'Tom Post 5', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
apost6 = Post.create(author: user1, title: 'Tom Post 6', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')

bpost1 = Post.create(author: user2, title: 'Lilly Post 1', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
bpost2 = Post.create(author: user2, title: 'Lilly Post 2', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
bpost3 = Post.create(author: user2, title: 'Lilly Post 3', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
bpost4 = Post.create(author: user2, title: 'Lilly Post 4', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
bpost5 = Post.create(author: user2, title: 'Lilly Post 5', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
bpost6 = Post.create(author: user2, title: 'Lilly Post 6', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')

cpost1 = Post.create(author: user3, title: 'Sandra Post 1', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
cpost2 = Post.create(author: user3, title: 'Sandra Post 2', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
cpost3 = Post.create(author: user3, title: 'Sandra Post 3', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
cpost4 = Post.create(author: user3, title: 'Sandra Post 4', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
cpost5 = Post.create(author: user3, title: 'Sandra Post 5', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
cpost6 = Post.create(author: user3, title: 'Sandra Post 6', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')

dpost1 = Post.create(author: user4, title: 'Peter Post 1', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
dpost2 = Post.create(author: user4, title: 'Peter Post 2', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
dpost3 = Post.create(author: user4, title: 'Peter Post 3', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
dpost4 = Post.create(author: user4, title: 'Peter Post 4', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
dpost5 = Post.create(author: user4, title: 'Peter Post 5', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
dpost6 = Post.create(author: user4, title: 'Peter Post 6', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')

epost1 = Post.create(author: user5, title: 'John Post 1', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
epost2 = Post.create(author: user5, title: 'John Post 2', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
epost3 = Post.create(author: user5, title: 'John Post 3', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
epost4 = Post.create(author: user5, title: 'John Post 4', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
epost5 = Post.create(author: user5, title: 'John Post 5', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')
epost6 = Post.create(author: user5, title: 'John Post 6', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed quam vulputate, interdum eros vulputate, eleifend quam. Donec ultrices nibh non odio interdum, eu tincidunt mi porttitor. Donec sodales sem dui, non maximus nunc rutrum et. Vestibulum non lectus erat. Cras vehicula magna et lacus pharetra bibendum.')

# Comments information
Comment.create(author: user1, post: apost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost2, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost2, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost3, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost3, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost4, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost4, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost5, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost5, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost6, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user1, post: apost6, text: 'Proin a turpis leo. Praesent ut ante risus.')

Comment.create(author: user2, post: bpost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost2, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost2, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost3, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost3, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost4, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost4, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost5, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost5, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost6, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user2, post: bpost6, text: 'Proin a turpis leo. Praesent ut ante risus.')

Comment.create(author: user3, post: cpost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost2, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost2, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost3, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost3, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost4, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost4, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost5, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost5, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost6, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user3, post: cpost6, text: 'Proin a turpis leo. Praesent ut ante risus.')

Comment.create(author: user4, post: dpost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost2, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost2, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost3, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost3, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost4, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost4, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost5, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost5, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost6, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user4, post: dpost6, text: 'Proin a turpis leo. Praesent ut ante risus.')

Comment.create(author: user5, post: epost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost1, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost2, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost2, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost3, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost3, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost4, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost4, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost5, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost5, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost6, text: 'Proin a turpis leo. Praesent ut ante risus.')
Comment.create(author: user5, post: epost6, text: 'Proin a turpis leo. Praesent ut ante risus.')

# Likes information
Like.create(author: user1, post: apost1)
Like.create(author: user1, post: apost2)
Like.create(author: user1, post: apost3)
Like.create(author: user1, post: apost4)
Like.create(author: user1, post: apost5)
Like.create(author: user1, post: apost6)

Like.create(author: user2, post: bpost1)
Like.create(author: user2, post: bpost2)
Like.create(author: user2, post: bpost3)
Like.create(author: user2, post: bpost4)
Like.create(author: user2, post: bpost5)
Like.create(author: user2, post: bpost6)


Like.create(author: user3, post: cpost1)
Like.create(author: user3, post: cpost2)
Like.create(author: user3, post: cpost3)
Like.create(author: user3, post: cpost4)
Like.create(author: user3, post: cpost5)
Like.create(author: user3, post: cpost6)

Like.create(author: user4, post: dpost1)
Like.create(author: user4, post: dpost2)
Like.create(author: user4, post: dpost3)
Like.create(author: user4, post: dpost4)
Like.create(author: user4, post: dpost5)
Like.create(author: user4, post: dpost6)

Like.create(author: user5, post: epost1)
Like.create(author: user5, post: epost2)
Like.create(author: user5, post: epost3)
Like.create(author: user5, post: epost4)
Like.create(author: user5, post: epost5)
Like.create(author: user5, post: epost6)